name: Django CI/CD

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Local Server
        run: |
          cd ~/myproject
          git pull origin main
          docker compose down
          docker compose up -d --build
